export const SET_SPINNER_FALSE = "SET_SPINNER_FALSE"
export const SET_SPINNER_TRUE = "SET_SPINNER_TRUE"

export const SHOW_SNACKBAR = "SHOW_SNACKBAR"
export const HIDE_SNACKBAR = "HIDE_SNACKBAR"
export const ADD_CATEGORY_LIST="ADD_CATEGORY_LIST";